<Project>
  <PropertyGroup>
    <MetalamaCompilerVersion Condition="'$(MetalamaCompilerVersion)' == ''">2026.1.18</MetalamaCompilerVersion>
    <MetalamaVersion Condition="'$(MetalamaVersion)' == ''">2026.1.28</MetalamaVersion>
    <MetalamaCommunityReleaseVersion>2026.1.28</MetalamaCommunityReleaseVersion>
    <MetalamaCommunityReleaseMainVersion>2026.1.28</MetalamaCommunityReleaseMainVersion>
  </PropertyGroup>
</Project>