<Project>
  <PropertyGroup>
    <MetalamaCompilerVersion Condition="'$(MetalamaCompilerVersion)' == ''">2026.1.19</MetalamaCompilerVersion>
    <MetalamaVersion Condition="'$(MetalamaVersion)' == ''">2026.1.29</MetalamaVersion>
    <MetalamaCommunityReleaseVersion>2026.1.29</MetalamaCommunityReleaseVersion>
    <MetalamaCommunityReleaseMainVersion>2026.1.29</MetalamaCommunityReleaseMainVersion>
  </PropertyGroup>
</Project>